apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: book-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: auth:latest
          ports:
            - containerPort: 4000
          env:
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: common-config
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: book-library
spec:
  ports:
    - port: 4000
  selector:
    app: auth