apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendation
  namespace: book-library
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
        - name: recommendation
          image: recommendation:latest
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: recommendation
  namespace: book-library
spec:
  ports:
    - port: 5000
  selector:
    app: recommendation